{{- if not .Values.bootstrapOnly }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 8080
{{- end }}
