{{- if not .Values.bootstrapOnly }}
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: {{ .Values.namespace }}
  labels:
    app: garage
spec:
  clusterIP: None
  selector:
    app: garage
  ports:
    - name: s3
      port: 3900
      targetPort: s3
    - name: rpc
      port: 3901
      targetPort: rpc
    - name: web
      port: 3902
      targetPort: web
    - name: admin
      port: 3903
      targetPort: admin
{{- end }}
