{{- if not .Values.bootstrapOnly }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garage
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.assetsHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garage
                port:
                  number: 3902
{{- end }}
