{{- if not .Values.bootstrapOnly }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
{{- end }}
