apiVersion: v2
name: games-catalog
description: Orkestrasi games-catalog di Kubernetes - Postgres, migrasi Prisma, api, admin, public, Garage, Prometheus, Grafana, Ingress, HPA
type: application
version: 0.1.0
